/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controller.ProjectController;
import controller.TaskController;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.table.TableCellRenderer;
import model.Project;
import model.Task;
import util.ButtonDelete;
import util.DeadlineColumnCellRenderer;
import util.ButtonEdit;
import util.TaskTableModel;


/**
 *
 * @author Pichau
 */
public class MainScreen extends javax.swing.JFrame {

    ProjectController projectController;
    TaskController taskController;
    
    DefaultListModel projectsModel;
    TaskTableModel taskModel;
    
    
    
    public MainScreen() {
        initComponents();
      
        initDataController();
        initComponetsModel();
        
        decorateTableTask();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jScrollPaneTasks = new javax.swing.JScrollPane();
        jTableTasks = new javax.swing.JTable();
        jPanel1ToolBar = new javax.swing.JPanel();
        jLabel1ToolBarTitle = new javax.swing.JLabel();
        jLabel2ToolBarSubtitle = new javax.swing.JLabel();
        jPanel2Projects = new javax.swing.JPanel();
        jLabel3ProjectsTitle = new javax.swing.JLabel();
        jLabel5ProjectsAdd = new javax.swing.JLabel();
        jPanel3Tasks = new javax.swing.JPanel();
        jLabel4TasksTitle = new javax.swing.JLabel();
        jLabel6TasksAdd = new javax.swing.JLabel();
        jPanel4ProjectList = new javax.swing.JPanel();
        jScrollPane1Projects = new javax.swing.JScrollPane();
        jList1Projects = new javax.swing.JList<>();
        jPanel5 = new javax.swing.JPanel();
        jPanelEmptyList = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        jLabel10.setText("jLabel10");

        jScrollPaneTasks.setBackground(new java.awt.Color(255, 255, 255));

        jTableTasks.setAutoCreateRowSorter(true);
        jTableTasks.setBackground(new java.awt.Color(255, 255, 255));
        jTableTasks.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTableTasks.setForeground(new java.awt.Color(0, 0, 0));
        jTableTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Descrição", "Prazo", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTasks.setGridColor(new java.awt.Color(255, 255, 255));
        jTableTasks.setRowHeight(50);
        jTableTasks.setSelectionBackground(new java.awt.Color(0, 152, 102));
        jTableTasks.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTableTasks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableTasks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableTasks.setShowGrid(true);
        jTableTasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTasksMouseClicked(evt);
            }
        });
        jScrollPaneTasks.setViewportView(jTableTasks);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 800));

        jPanel1ToolBar.setBackground(new java.awt.Color(0, 153, 102));

        jLabel1ToolBarTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1ToolBarTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1ToolBarTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/tick.png"))); // NOI18N
        jLabel1ToolBarTitle.setText(" ToDo App");

        jLabel2ToolBarSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2ToolBarSubtitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2ToolBarSubtitle.setText("Anote tudo, não esqueça nada!");

        javax.swing.GroupLayout jPanel1ToolBarLayout = new javax.swing.GroupLayout(jPanel1ToolBar);
        jPanel1ToolBar.setLayout(jPanel1ToolBarLayout);
        jPanel1ToolBarLayout.setHorizontalGroup(
            jPanel1ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1ToolBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2ToolBarSubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1ToolBarTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1ToolBarLayout.setVerticalGroup(
            jPanel1ToolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1ToolBarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1ToolBarTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2ToolBarSubtitle)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel2Projects.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2Projects.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3ProjectsTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3ProjectsTitle.setForeground(new java.awt.Color(0, 152, 102));
        jLabel3ProjectsTitle.setText("  Projetos");

        jLabel5ProjectsAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5ProjectsAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add.png"))); // NOI18N
        jLabel5ProjectsAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5ProjectsAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2ProjectsLayout = new javax.swing.GroupLayout(jPanel2Projects);
        jPanel2Projects.setLayout(jPanel2ProjectsLayout);
        jPanel2ProjectsLayout.setHorizontalGroup(
            jPanel2ProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2ProjectsLayout.createSequentialGroup()
                .addComponent(jLabel3ProjectsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5ProjectsAdd)
                .addContainerGap())
        );
        jPanel2ProjectsLayout.setVerticalGroup(
            jPanel2ProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2ProjectsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2ProjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5ProjectsAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jLabel3ProjectsTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3Tasks.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3Tasks.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4TasksTitle.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4TasksTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4TasksTitle.setForeground(new java.awt.Color(0, 152, 102));
        jLabel4TasksTitle.setText("  Tarefas");

        jLabel6TasksAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add.png"))); // NOI18N
        jLabel6TasksAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6TasksAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3TasksLayout = new javax.swing.GroupLayout(jPanel3Tasks);
        jPanel3Tasks.setLayout(jPanel3TasksLayout);
        jPanel3TasksLayout.setHorizontalGroup(
            jPanel3TasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3TasksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4TasksTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6TasksAdd)
                .addContainerGap())
        );
        jPanel3TasksLayout.setVerticalGroup(
            jPanel3TasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3TasksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3TasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4TasksTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3TasksLayout.createSequentialGroup()
                        .addComponent(jLabel6TasksAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4ProjectList.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4ProjectList.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jList1Projects.setBackground(new java.awt.Color(255, 255, 255));
        jList1Projects.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jList1Projects.setForeground(new java.awt.Color(0, 0, 0));
        jList1Projects.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1Projects.setFixedCellHeight(50);
        jList1Projects.setSelectionBackground(new java.awt.Color(0, 152, 102));
        jList1Projects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1ProjectsMouseClicked(evt);
            }
        });
        jScrollPane1Projects.setViewportView(jList1Projects);

        javax.swing.GroupLayout jPanel4ProjectListLayout = new javax.swing.GroupLayout(jPanel4ProjectList);
        jPanel4ProjectList.setLayout(jPanel4ProjectListLayout);
        jPanel4ProjectListLayout.setHorizontalGroup(
            jPanel4ProjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4ProjectListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1Projects)
                .addContainerGap())
        );
        jPanel4ProjectListLayout.setVerticalGroup(
            jPanel4ProjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4ProjectListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1Projects))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanelEmptyList.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/lists.png"))); // NOI18N
        jLabel7.setToolTipText("");

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Nenhuma Tarefa por aqui :D");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Clique no botão \"+\" para adicionar uma nova tarefa");

        javax.swing.GroupLayout jPanelEmptyListLayout = new javax.swing.GroupLayout(jPanelEmptyList);
        jPanelEmptyList.setLayout(jPanelEmptyListLayout);
        jPanelEmptyListLayout.setHorizontalGroup(
            jPanelEmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelEmptyListLayout.setVerticalGroup(
            jPanelEmptyListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmptyListLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(216, Short.MAX_VALUE))
        );

        jPanel5.add(jPanelEmptyList, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1ToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2Projects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4ProjectList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3Tasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1ToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2Projects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3Tasks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4ProjectList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5ProjectsAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5ProjectsAddMouseClicked
        // TODO add your handling code here:
        ProjectDialogScreen projectDialogScreen = new ProjectDialogScreen(this, rootPaneCheckingEnabled);
        projectDialogScreen.setVisible(true);
        
        projectDialogScreen.addWindowListener(new WindowAdapter(){
            public void windowClosed(WindowEvent e){
                loadProjects();
            }  
        });
    }//GEN-LAST:event_jLabel5ProjectsAddMouseClicked

    private void jLabel6TasksAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6TasksAddMouseClicked
        // TODO add your handling code here:
        TaskDialogScreen taskDialogScreen = new TaskDialogScreen(this, rootPaneCheckingEnabled);
        
        int projectIndex = jList1Projects.getSelectedIndex();
        Project project = (Project) projectsModel.get(projectIndex);
        taskDialogScreen.setProject(project);
        
        taskDialogScreen.setVisible(true);
        
        taskDialogScreen.addWindowListener(new WindowAdapter() {
            public void windowClosed(WindowEvent e) {
                int projectIndex = jList1Projects.getSelectedIndex();
                Project project = (Project) projectsModel.get(projectIndex);
                loadTasks(project.getId());
            }
        });
    }//GEN-LAST:event_jLabel6TasksAddMouseClicked
    
    private void jTableTasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTasksMouseClicked
        // TODO add your handling code here:
        int rowIndex = jTableTasks.rowAtPoint(evt.getPoint());
        int columnIndex = jTableTasks.columnAtPoint(evt.getPoint());
        int projectIndex = jList1Projects.getSelectedIndex();
        Project project = (Project) projectsModel.get(projectIndex);
        Task task = taskModel.getTasks().get(rowIndex);
        
        switch(columnIndex){
            case 3:
                taskController.update(task);
                break;
            case 4:
                TaskDialogScreen taskDialogScreen = new TaskDialogScreen(this, rootPaneCheckingEnabled);
                taskDialogScreen.addWindowListener(new WindowAdapter() {
                    public void windowOpened(WindowEvent e) {
                    loadTasks(project.getId());
                    taskController.update(task);
                    }
                });
                taskDialogScreen.setVisible(true);
   
            /*case 5:
                taskController.removeByID(task.getId());
                taskModel.getTasks().remove(task);
                loadTasks(project.getId());
                break; */ 
        }
    }//GEN-LAST:event_jTableTasksMouseClicked

    private void jList1ProjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1ProjectsMouseClicked
        // TODO add your handling code here:
        int projectIndex = jList1Projects.getSelectedIndex();
        Project project = (Project)projectsModel.get(projectIndex);
        loadTasks(project.getId());
    }//GEN-LAST:event_jList1ProjectsMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel1ToolBarTitle;
    private javax.swing.JLabel jLabel2ToolBarSubtitle;
    private javax.swing.JLabel jLabel3ProjectsTitle;
    private javax.swing.JLabel jLabel4TasksTitle;
    private javax.swing.JLabel jLabel5ProjectsAdd;
    private javax.swing.JLabel jLabel6TasksAdd;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1Projects;
    private javax.swing.JPanel jPanel1ToolBar;
    private javax.swing.JPanel jPanel2Projects;
    private javax.swing.JPanel jPanel3Tasks;
    private javax.swing.JPanel jPanel4ProjectList;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelEmptyList;
    private javax.swing.JScrollPane jScrollPane1Projects;
    private javax.swing.JScrollPane jScrollPaneTasks;
    private javax.swing.JTable jTableTasks;
    // End of variables declaration//GEN-END:variables

    public void decorateTableTask(){
        
        //Customizando o Header da table de Tarefas
        jTableTasks.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        jTableTasks.getTableHeader().setBackground(new Color(0, 153, 102));
        jTableTasks.getTableHeader().setForeground(new Color(255, 255, 255));
        
        jTableTasks.getColumnModel().getColumn(2)
                .setCellRenderer(new DeadlineColumnCellRenderer());
       
        /*ImageIcon icon;
        icon = new ImageIcon("resources/edit.png");
        setIconImage(icon.getImage());*/
        
        //jTableTasks.getColumn(icon);
        
        jTableTasks.getColumnModel().getColumn(4).setCellRenderer
        (new ButtonEdit("edit"));
        jTableTasks.getColumnModel().getColumn(5).setCellRenderer
        (new ButtonDelete("delete"));
        //Criando um sort automático para as colunas da table
        //jTableTasks.setAutoCreateRowSorter(true);*/
    }
    
    public void initDataController (){
        projectController = new ProjectController();
        taskController = new TaskController ();
    }
    
    public void initComponetsModel(){
        projectsModel = new DefaultListModel ();
        loadProjects();
        
        taskModel = new TaskTableModel ();
        jTableTasks.setModel(taskModel);
        
        if (!projectsModel.isEmpty()){
            jList1Projects.setSelectedIndex(0);
            int projectIndex = jList1Projects.getSelectedIndex();
            Project project = (Project) projectsModel.get(projectIndex);
            loadTasks(project.getId());
        }
    }
    public void loadTask (int IdProject, int id){
        List<Task> tasks = taskController.getAll(IdProject);
        taskModel.setTasks((List<Task>) tasks.get(id));
        
    }
    public void loadTasks (int IdProject){
        List<Task> tasks = taskController.getAll(IdProject);
        taskModel.setTasks(tasks);
        
        showJTableTasks(!tasks.isEmpty());
        
    }
    
    private void showJTableTasks(boolean hasTasks){
        if(hasTasks){
            // Se Tarefas foram carregadas
            if(jPanelEmptyList.isVisible()){
                jPanelEmptyList.setVisible(false);
                jPanel5.remove(jPanelEmptyList);
            }
            
            jPanel5.add(jScrollPaneTasks);
            jScrollPaneTasks.setVisible(true);
            jScrollPaneTasks.setSize(jPanel5.getWidth(), jPanel5.getHeight());
        } else {
            if(jScrollPaneTasks.isVisible()){
                jScrollPaneTasks.setVisible(false);
                jPanel5.remove(jScrollPaneTasks);
            }
            
            jPanel5.add(jPanelEmptyList);
            jPanelEmptyList.setVisible(true);
            jPanelEmptyList.setSize(jPanel5.getWidth(), jPanel5.getHeight());
        }
    }
    
    
    public void loadProjects(){
       List<Project> projects = projectController.getAll();
       
       projectsModel.clear();
       
       for (int i =0; i< projects.size(); i++){
           Project project = projects.get(i);
           projectsModel.addElement(project);
           
       }
       jList1Projects.setModel(projectsModel);
    }

}
